package cmd

import (
	"fmt"
	"os"
	"runtime"
	"strings"
	"sync"
	"sync/atomic"

	"github.com/spf13/cobra"

	"github.com/KashifKhn/remove-comments/cli/internal/config"
	"github.com/KashifKhn/remove-comments/cli/internal/diff"
	"github.com/KashifKhn/remove-comments/cli/internal/generated"
	"github.com/KashifKhn/remove-comments/cli/internal/languages"
	"github.com/KashifKhn/remove-comments/cli/internal/output"
	"github.com/KashifKhn/remove-comments/cli/internal/parser"
	"github.com/KashifKhn/remove-comments/cli/internal/remover"
	"github.com/KashifKhn/remove-comments/cli/internal/walker"
)

var rootCmd = &cobra.Command{
	Use:   "remove-comments [path]",
	Short: "Remove all comments from source files in a directory",
	Long: `Remove all comments from source code files in a directory tree.

Uses Tree-sitter AST parsing (never regex) to find comments, so strings
and nested syntax are never corrupted. Respects .gitignore at every level.
Skips generated files (*.g.dart, *.pb.go, *_pb2.py, ...) and files with
"DO NOT EDIT" / "Generated by" headers by default.

Runs in dry-run mode by default: shows what would change.
Pass --write to modify files on disk.

Supported languages: run --list-langs to see all (18 languages incl.
go, python, typescript, java, rust, c/c++, dart, ...).

Configuration: a .remove-comments.yaml file at the project root
(discovered by searching upward from the target path) can persist
exclude, include, langs, skip-generated and max-file-size settings.
CLI flags always override config file values.`,
	Example: `  # Dry-run: preview what would change (no files modified)
  remove-comments .
  remove-comments --diff .

  # Apply changes
  remove-comments --write .
  remove-comments --write ./src

  # Target only some files
  remove-comments --include "src/**" --include "*.java" .
  remove-comments --exclude "*.g.dart" --exclude "*_test.go" .
  remove-comments --include "src/**" --exclude "vendor/**" .

  # Target only some languages (comma-separated)
  remove-comments --lang go .
  remove-comments --lang go,java,typescript .

  # List all supported languages
  remove-comments --list-langs

  # Process generated files too (skipped by default)
  remove-comments --no-skip-generated .

  # Use a config file (or disable config discovery)
  remove-comments --config ~/my-rules.yaml .
  remove-comments --no-config .

  # Quiet mode: only the final summary line
  remove-comments --quiet .

  # Control parallelism
  remove-comments --jobs 4 .`,
	Args: cobra.MaximumNArgs(1),
	RunE: run,
}

var (
	flagWrite           bool
	flagQuiet           bool
	flagDiff            bool
	flagLang            string
	flagJobs            int
	flagMaxFileSize     int64
	flagExclude         []string
	flagInclude         []string
	flagNoSkipGenerated bool
	flagNoConfig        bool
	flagConfigPath      string
	flagListLangs       bool
)

func Execute(version string) {
	rootCmd.Version = version
	registerUpgradeCmd(version)
	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

func init() {
	rootCmd.Flags().BoolVarP(&flagWrite, "write", "w", false,
		"Write changes to disk (without this flag, only preview)")
	rootCmd.Flags().BoolVarP(&flagQuiet, "quiet", "q", false,
		"Print only the final summary line")
	rootCmd.Flags().BoolVarP(&flagDiff, "diff", "d", false,
		"Show unified diff for each changed file")
	rootCmd.Flags().StringVar(&flagLang, "lang", "",
		"Only process these languages, comma-separated (e.g. \"go,java\"; see --list-langs)")
	rootCmd.Flags().StringArrayVarP(&flagExclude, "exclude", "e", nil,
		"Skip files matching a glob (repeatable, e.g. -e '*.g.dart' -e 'vendor/**'; supports **)")
	rootCmd.Flags().StringArrayVar(&flagInclude, "include", nil,
		"Only process files matching a glob (repeatable, e.g. --include 'src/**'; --exclude wins on conflict)")
	rootCmd.Flags().BoolVar(&flagNoSkipGenerated, "no-skip-generated", false,
		"Process generated files too (*.g.dart, *.pb.go, 'DO NOT EDIT' headers are skipped by default)")
	rootCmd.Flags().BoolVar(&flagListLangs, "list-langs", false,
		"List all supported languages and exit")
	rootCmd.Flags().IntVarP(&flagJobs, "jobs", "j", 0,
		"Number of parallel workers (default: NumCPU)")
	rootCmd.Flags().Int64Var(&flagMaxFileSize, "max-file-size", 10*1024*1024,
		"Skip files larger than this size in bytes (10485760 = 10 MB)")
	rootCmd.Flags().StringVar(&flagConfigPath, "config", "",
		"Path to a config file (default: search for .remove-comments.yaml upward from [path])")
	rootCmd.Flags().BoolVar(&flagNoConfig, "no-config", false,
		"Do not load any config file")
}

func run(cmd *cobra.Command, args []string) error {
	if flagListLangs {
		for _, name := range languages.Names() {
			fmt.Fprintln(cmd.OutOrStdout(), name)
		}
		return nil
	}

	root := "."
	if len(args) == 1 {
		root = args[0]
	}

	if _, err := os.Stat(root); err != nil {
		return err
	}

	cfg, err := loadConfig(root)
	if err != nil {
		return err
	}

	langNames := parseLangs(flagLang, cfg.Langs)
	filter := languages.NewLangFilter(langNames)
	if err := filter.Validate(); err != nil {
		return err
	}

	opts := walker.Options{
		Langs:       filter.Names(),
		MaxFileSize: resolveMaxFileSize(cmd, cfg.MaxFileSize),
		Exclude:     mergeStrings(cfg.Exclude, flagExclude),
		Include:     mergeStrings(cfg.Include, flagInclude),
	}

	skipGenerated := !flagNoSkipGenerated
	if cfg.SkipGenerated != nil {
		skipGenerated = *cfg.SkipGenerated && !flagNoSkipGenerated
	}

	jobs := flagJobs
	if jobs <= 0 {
		jobs = runtime.NumCPU()
	}

	entries, walkErrs := walker.Walk(root, opts)
	if len(walkErrs) > 0 {
		for _, e := range walkErrs {
			fmt.Fprintf(os.Stderr, "walk error: %v\n", e)
		}
	}

	printer := output.New(os.Stdout, flagQuiet, flagWrite, flagDiff)

	var (
		mu      sync.Mutex
		changed int32
		errors  int32
		skipped int32
		total   int32
	)

	work := make(chan walker.FileEntry, jobs*2)
	var wg sync.WaitGroup

	for i := 0; i < jobs; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for entry := range work {
				atomic.AddInt32(&total, 1)

				src, err := os.ReadFile(entry.Path)
				if err != nil {
					atomic.AddInt32(&errors, 1)
					mu.Lock()
					printer.Error(entry.Path, err)
					mu.Unlock()
					continue
				}

				if skipGenerated && generated.IsGenerated(entry.Path, src) {
					atomic.AddInt32(&skipped, 1)
					mu.Lock()
					printer.Skipped(entry.Path, "generated")
					mu.Unlock()
					continue
				}

				ranges, err := parser.Parse(src, entry.Lang)
				if err != nil {
					atomic.AddInt32(&errors, 1)
					mu.Lock()
					printer.Error(entry.Path, err)
					mu.Unlock()
					continue
				}

				after := remover.Remove(src, ranges)
				result := diff.Compute(entry.Path, src, after)

				if result.Changed {
					if flagWrite {
						info, statErr := os.Stat(entry.Path)
						if statErr != nil {
							atomic.AddInt32(&errors, 1)
							mu.Lock()
							printer.Error(entry.Path, statErr)
							mu.Unlock()
							continue
						}
						if info.Mode()&0o200 == 0 {
							mu.Lock()
							printer.File(result)
							mu.Unlock()
							continue
						}
						if writeErr := os.WriteFile(entry.Path, result.After, info.Mode()); writeErr != nil {
							atomic.AddInt32(&errors, 1)
							mu.Lock()
							printer.Error(entry.Path, writeErr)
							mu.Unlock()
							continue
						}
					}
					atomic.AddInt32(&changed, 1)
				}

				mu.Lock()
				printer.File(result)
				mu.Unlock()
			}
		}()
	}

	for _, e := range entries {
		work <- e
	}
	close(work)
	wg.Wait()

	printer.Summary(int(changed), int(skipped), int(errors), int(total))
	return nil
}

func loadConfig(root string) (config.Config, error) {
	if flagNoConfig {
		return config.Config{}, nil
	}
	path := flagConfigPath
	if path == "" {
		path = config.Discover(root)
	}
	if path == "" {
		return config.Config{}, nil
	}
	return config.Load(path)
}

func parseLangs(flagValue string, cfgLangs []string) []string {
	if flagValue != "" {
		return strings.Split(flagValue, ",")
	}
	return cfgLangs
}

func resolveMaxFileSize(cmd *cobra.Command, cfgValue int64) int64 {
	if cmd.Flags().Changed("max-file-size") {
		return flagMaxFileSize
	}
	if cfgValue > 0 {
		return cfgValue
	}
	return flagMaxFileSize
}

func mergeStrings(cfgVals, flagVals []string) []string {
	if len(cfgVals) == 0 {
		return flagVals
	}
	if len(flagVals) == 0 {
		return cfgVals
	}
	seen := map[string]bool{}
	out := make([]string, 0, len(cfgVals)+len(flagVals))
	for _, v := range append(cfgVals, flagVals...) {
		if !seen[v] {
			seen[v] = true
			out = append(out, v)
		}
	}
	return out
}
